<script lang="ts">
  import { open } from '@tauri-apps/plugin-dialog';
  import {
    envExampleFromVault,
    envExampleFromFile,
    envExampleApply,
    type EnvExampleProposal,
    type EnvExampleApplyReport,
    type KeyMetadataDto
  } from '$lib/api';

  interface Props {
    keys: KeyMetadataDto[];
    onClose: () => void;
    onApplied: (message: string) => void;
    onSessionExpired: () => void;
  }
  let { keys, onClose, onApplied, onSessionExpired }: Props = $props();

  type Mode = 'vault' | 'file';
  let mode = $state<Mode>('vault');

  // Common
  let targetDir = $state('');
  let filename = $state('.env.example');
  let includeHeader = $state(true);
  let busy = $state(false);
  let error = $state<string | null>(null);
  let proposal = $state<EnvExampleProposal | null>(null);
  let applied = $state<EnvExampleApplyReport | null>(null);
  let confirmingOverwrite = $state(false);

  // Mode A — Vault
  let selectedKey = $state<Record<string, boolean>>({});
  let includeHolsterComments = $state(false);

  // Mode B — Source file
  let sourcePath = $state('');

  const selectedIds = $derived(keys.filter((k) => selectedKey[k.id]).map((k) => k.id));

  function sessionExpired(msg: string) {
    return msg.toLowerCase().includes('session expired') || msg.toLowerCase().includes('session is invalid');
  }

  function resetProposal() {
    proposal = null;
    applied = null;
    confirmingOverwrite = false;
  }

  function switchMode(next: Mode) {
    mode = next;
    resetProposal();
    error = null;
  }

  async function chooseTargetFolder() {
    error = null;
    try {
      const picked = await open({
        directory: true,
        multiple: false,
        title: 'Choose where to write .env.example'
      });
      if (typeof picked === 'string') {
        targetDir = picked;
        resetProposal();
      }
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
  }

  async function chooseSourceFile() {
    error = null;
    try {
      const picked = await open({
        directory: false,
        multiple: false,
        title: 'Choose source .env* file'
      });
      if (typeof picked === 'string') {
        sourcePath = picked;
        resetProposal();
      }
    } catch (e) {
      error = e instanceof Error ? e.message : String(e);
    }
  }

  async function buildProposal() {
    error = null;
    proposal = null;
    applied = null;
    confirmingOverwrite = false;
    busy = true;
    try {
      if (mode === 'vault') {
        if (selectedIds.length === 0) {
          error = 'Select at least one vault key.';
          busy = false;
          return;
        }
        proposal = await envExampleFromVault({
          key_ids: selectedIds,
          include_holster_comments: includeHolsterComments
        });
      } else {
        if (!sourcePath.trim()) {
          error = 'Pick a source .env file.';
          busy = false;
          return;
        }
        proposal = await envExampleFromFile({ source_path: sourcePath.trim() });
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (sessionExpired(msg)) {
        onSessionExpired();
        return;
      }
      error = msg;
    } finally {
      busy = false;
    }
  }

  async function runApply(allowOverwrite = false) {
    if (!proposal) return;
    error = null;
    busy = true;
    try {
      const result = await envExampleApply({
        target_dir: targetDir.trim(),
        filename: filename.trim() || null,
        lines: proposal.lines,
        overwrite: allowOverwrite,
        include_header_comments: includeHeader
      });
      applied = result;
      confirmingOverwrite = false;
      onApplied(
        `Wrote ${result.line_count} entr${result.line_count === 1 ? 'y' : 'ies'} to ${result.target_path}` +
          (result.overwrote ? ' (overwrote existing)' : '')
      );
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      if (sessionExpired(msg)) {
        onSessionExpired();
        return;
      }
      // Detect the "already exists" refusal and surface a confirm step
      if (msg.includes('already exists')) {
        confirmingOverwrite = true;
        error = null;
      } else {
        error = msg;
      }
    } finally {
      busy = false;
    }
  }

  // Build a preview of the body the apply will write.
  const previewBody = $derived.by(() => {
    if (!proposal) return '';
    const header = includeHeader
      ? '# Generated by Holster — committable template, no values.\n' +
        '# Each variable below is required by this project. Set values\n' +
        '# in .env.local (which should be gitignored — see Holster\'s\n' +
        '# gitignore helper) and never commit them.\n\n'
      : '';
    const blocks = proposal.lines.map((l) => {
      const c = l.comment ? `# ${l.comment}\n` : '';
      return `${c}${l.name}=`;
    });
    return header + blocks.join('\n\n') + '\n';
  });

  function onBackdropClick(e: MouseEvent) {
    if (e.target === e.currentTarget) onClose();
  }
  function onKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') onClose();
  }
</script>

<svelte:window onkeydown={onKeydown} />

<div class="modal-backdrop" role="presentation" onclick={onBackdropClick}>
  <div class="modal wide-modal" role="dialog" aria-modal="true" aria-labelledby="envex-title">
    <h2 id="envex-title">Generate .env.example</h2>
    <p class="muted" style="margin-bottom: 14px;">
      Produce a committable template that lists the env-var <em>names</em> a project needs,
      with placeholder values only. Holster never writes a real secret value into a
      <code>.env.example</code>.
    </p>

    <div class="mode-tabs">
      <button
        type="button"
        class:active={mode === 'vault'}
        onclick={() => switchMode('vault')}
        disabled={busy}
      >From vault</button>
      <button
        type="button"
        class:active={mode === 'file'}
        onclick={() => switchMode('file')}
        disabled={busy}
      >From existing .env file</button>
    </div>

    {#if mode === 'vault'}
      <div class="field">
        <div class="field-label">Vault keys to include</div>
        {#if keys.length === 0}
          <p class="muted">No keys in vault yet. Add one first, or use "From existing .env file" mode.</p>
        {:else}
          <div class="key-picker">
            {#each keys as k (k.id)}
              <label class="check-row">
                <input type="checkbox" bind:checked={selectedKey[k.id]} />
                <span>
                  <strong>{k.label}</strong>
                  <span class="provider-badge">{k.provider}</span>
                  <span class="muted">{k.project_tag ?? 'no project'}</span>
                </span>
              </label>
            {/each}
          </div>
        {/if}
      </div>
      <div class="field">
        <label class="check-row inline">
          <input type="checkbox" bind:checked={includeHolsterComments} />
          <span>
            Include Holster source comments
            <span class="muted" style="font-size: 11px;">
              (e.g. "# stored in Holster as openai / Personal" — references provider+label, never value)
            </span>
          </span>
        </label>
      </div>
    {:else}
      <div class="field">
        <label for="source-path">Source .env file</label>
        <div class="path-picker">
          <input
            id="source-path"
            type="text"
            bind:value={sourcePath}
            placeholder="/path/to/some-project/.env.local"
            disabled={busy}
          />
          <button type="button" onclick={chooseSourceFile} disabled={busy}>Browse…</button>
        </div>
        <p class="muted" style="font-size: 12px; margin-top: 6px;">
          Holster reads only the variable <em>names</em> from this file. The parser stops at the
          first <code>=</code> on each line; values are never read past that point.
          The file must be named <code>.env</code> or <code>.env.*</code>.
        </p>
      </div>
    {/if}

    <div class="field two-col">
      <div>
        <label for="envex-target-dir">Target folder</label>
        <div class="path-picker">
          <input
            id="envex-target-dir"
            type="text"
            bind:value={targetDir}
            placeholder="/Users/admin/my-project"
            disabled={busy}
          />
          <button type="button" onclick={chooseTargetFolder} disabled={busy}>Browse…</button>
        </div>
      </div>
      <div>
        <label for="envex-filename">File</label>
        <input id="envex-filename" type="text" bind:value={filename} placeholder=".env.example" />
      </div>
    </div>

    <div class="field">
      <label class="check-row inline">
        <input type="checkbox" bind:checked={includeHeader} />
        <span>Include explanatory header comment block</span>
      </label>
    </div>

    {#if error}
      <div class="error-box">{error}</div>
    {/if}

    {#if applied}
      <div class="apply-success">
        <strong>Wrote</strong> {applied.line_count} entr{applied.line_count === 1 ? 'y' : 'ies'} to
        <code>{applied.target_path}</code>{applied.overwrote ? ' (overwrote)' : ''}.
        {#if applied.audit_log_path}<br /><span class="muted small">Audit: {applied.audit_log_path}</span>{/if}
      </div>
    {/if}

    {#if proposal}
      <div class="proposal-box">
        <div class="proposal-head">
          <strong>{proposal.source_label}</strong>
          <span class="muted">
            {proposal.parsed_count} name{proposal.parsed_count === 1 ? '' : 's'}
            {#if proposal.skipped_count > 0} · {proposal.skipped_count} line{proposal.skipped_count === 1 ? '' : 's'} skipped (malformed){/if}
          </span>
        </div>
        <div class="preview-label">Preview (no values, will be written verbatim):</div>
        <pre>{previewBody}</pre>
      </div>
    {/if}

    {#if confirmingOverwrite}
      <div class="overwrite-confirm">
        <strong>⚠ Target file already exists.</strong>
        Overwriting will replace the existing <code>{filename}</code> in the target folder.
        Click <em>Overwrite</em> to confirm, or <em>Cancel</em> to keep the existing file.
      </div>
    {/if}

    <div class="modal-actions">
      <button type="button" class="ghost" onclick={onClose} disabled={busy}>Close</button>
      <button type="button" onclick={buildProposal} disabled={busy}>
        {busy ? 'Building…' : 'Preview'}
      </button>
      {#if confirmingOverwrite}
        <button type="button" onclick={() => (confirmingOverwrite = false)} class="ghost" disabled={busy}>Cancel</button>
        <button type="button" class="primary danger" onclick={() => runApply(true)} disabled={busy}>
          {busy ? 'Overwriting…' : 'Overwrite'}
        </button>
      {:else}
        <button
          type="button"
          class="primary"
          onclick={() => runApply(false)}
          disabled={busy || !proposal || !targetDir.trim()}
        >
          {busy ? 'Writing…' : 'Apply'}
        </button>
      {/if}
    </div>
  </div>
</div>

<style>
  .mode-tabs {
    display: flex;
    gap: 4px;
    margin-bottom: 14px;
    border-bottom: 1px solid #2a2a2a;
  }
  .mode-tabs button {
    background: transparent;
    border: none;
    color: #aaa;
    padding: 8px 14px;
    cursor: pointer;
    font-size: 13px;
    font-weight: 600;
    border-bottom: 2px solid transparent;
  }
  .mode-tabs button.active {
    color: #88c2ff;
    border-bottom-color: #88c2ff;
  }
  .mode-tabs button:hover:not(.active) {
    color: #ccc;
  }
  .proposal-box {
    margin: 14px 0;
    border: 1px solid #2a2a2a;
    border-radius: 6px;
    padding: 10px 12px;
    background: #0c0c0c;
  }
  .proposal-head {
    display: flex;
    justify-content: space-between;
    align-items: center;
    margin-bottom: 8px;
  }
  .preview-label {
    font-size: 12px;
    color: #888;
    margin: 8px 0 4px;
  }
  .proposal-box pre {
    margin: 0;
    color: #b6e5c4;
    font-size: 12px;
    white-space: pre-wrap;
    max-height: 28vh;
    overflow-y: auto;
  }
  .overwrite-confirm {
    border-left: 4px solid #cc8844;
    background: #2a1a0a;
    color: #ffb066;
    padding: 10px 12px;
    border-radius: 4px;
    margin: 10px 0 14px;
    font-size: 13px;
  }
  .apply-success {
    border-left: 4px solid #4a9d6c;
    background: #0e2317;
    color: #b6e5c4;
    padding: 10px 12px;
    border-radius: 4px;
    margin: 10px 0 14px;
    font-size: 13px;
  }
  .small {
    font-size: 11px;
  }
</style>
